include(ExternalProject)

ExternalProject_Add(
    ${BCOS_UTILITIES_PROJECT}
    PREFIX ${CMAKE_SOURCE_DIR}/deps
    GIT_REPOSITORY https://github.com/FISCO-BCOS/bcos-utilities.git
    GIT_TAG 67b4adc13b7ef6f9e1d70c32d34bc0a05364ec18
    BUILD_IN_SOURCE 1
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> -DCMAKE_INSTALL_LIBDIR=lib
    LOG_CONFIGURE 1
    LOG_BUILD 1
    LOG_INSTALL 1
)

ExternalProject_Get_Property(${BCOS_UTILITIES_PROJECT} INSTALL_DIR)
add_library(bcos-utilities STATIC IMPORTED)
set(BCOS_UTILITIES_LIBRARY ${INSTALL_DIR}/lib/libbcos-utilities.a)
set(BCOS_UTILITIES_INCLUDE_DIR ${INSTALL_DIR}/include)

file(MAKE_DIRECTORY ${INSTALL_DIR}/lib)  # Must exist.
file(MAKE_DIRECTORY ${BCOS_UTILITIES_INCLUDE_DIR})  # Must exist.

set_property(TARGET bcos-utilities PROPERTY IMPORTED_LOCATION ${BCOS_UTILITIES_LIBRARY})
set_property(TARGET bcos-utilities PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${BCOS_UTILITIES_INCLUDE_DIR})
set_property(TARGET bcos-utilities PROPERTY INTERFACE_LINK_LIBRARIES ${BOOST_LOG} ${BOOST_LOG_SETUP} ${BOOST_FILESYSTEM} ${BOOST_CHRONO} ${BOOST_THREAD} ${BOOST_SERIALIZATION} ${BOOST_IOSTREAMS} ${BOOST_SYSTEM} ${ZLIB})

add_dependencies(bcos-utilities ${BCOS_UTILITIES_PROJECT})
unset(INSTALL_DIR)
